### ISSUE TITLE
As a user, I want to search all content

### ISSUE THREAD

**Issue by jamiefolsom** [hofstra/coyote#2]
It should be possible to search content on the site. Let's use https://lunrjs.com/

**Comment by tezcatlipoca** [comment]
Closed after implementing Lunr - open new issues for changes.

**Comment by feralresearch** [comment]
Found issue: on non-existant search term search page should return 'not found' message - currently it gets stuck on 'Loading...'

update: Fixed this with: https://github.com/hofstra/coyote/pull/16

**Comment by SteveMarvin** [comment]
Not quite...if you enter "https://lunrjs.com/" as a search term, it searches forever.
