### ISSUE TITLE
Links are not visible enough

### ISSUE THREAD

**Issue by jamiefolsom** [hofstra/coyote#3]
Long list of posts, small font. Make font larger, maybe adjust color contrast slightly.

**Comment by feralresearch** [comment]
@jamiefolsom A couple of questions: 

1. Does this refer to a particular page or just overall? "Long list of posts" I think is "browse posts?"

2. Is this related to links not being links (for example look at "source" bottom of this page and you'll see a handful of links that are just written out as inline text) http://hofstra.github.io/coyote/sources/mesoamerican-coyote/images/Coyote-as-Human-detail/)

**Comment by jamiefolsom** [comment]
Good questions, @tezcatlipoca. This issue is definitely too terse. So were my notes, from which it came 😉 . The issue is that on: http://hofstra.github.io/coyote/browse/, the links are too small, and not clear enough as links. I'd welcome your thoughts on good solutions.
